apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2migrate
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: somefive/hello-world:dev
          env:
            - name: k1
              value: v1
            - name: k2
              value: v2